### ISSUE TITLE
A Transformer approach for Electricity Price Forecasting

### ISSUE THREAD

**Issue by libin0306** [OscarLlorente/positive_active_saliency_maps#1]
What role does this project play in this essay.

**Comment by osllogon** [comment]
None, it was a typo when writing, it is solved now in the last version of the manuscript https://arxiv.org/pdf/2403.16108.pdf. The code is the following repo:
https://github.com/osllogon/epf-transformers

Sorry for the inconvenience, closing this since now it is solved. If you have any other questions ping me or open another issue and I will be happy to help
